name: dgbuildenv
channels:
  - nodefaults
  - conda-forge
dependencies:
#  - mamba
  - python
  - compilers
  - cmake
  - bash
  - pybind11
  - numpy #Since somewhat (?) tied to pybind11?
  - tomli #not actually needed for py3.11+
  - pip # in case we need to install dgbuild itself via pip
# Developer tools:
#  - git
#  - gdb # not on OSX, here it is simpler to use lldb.
#  - valgrind

# For g4framework (includes openscenegraph to test G4OSG compilation):
  - matplotlib-base
  - zlib
  - geant4
  - expat
  - ncrystal
  - scipy # imported in PyAna
  - openscenegraph # for G4OSG compilation check.
  - hdf5 #Only for NMX+ACE, could be removed
#TODO: - mcpl

#NCrystal material generation only:
#  - ase
#  - pymatgen
#  - gemmi
#  - spglib
#  - pip

#TODO: Cleanup the stuff below:

#  - pip:
#    - ptpython==3.0.23
#  DGCODE_FORCEVAR_CC: clang
#  DGCODE_FORCEVAR_CXX: clang++
##
#unsolved: root, garfield, mantidpython
